var R=require("../../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(app)/lists/[id]/shop/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0v701_-._.js")
R.c("server/chunks/ssr/node_modules_09r9c10._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0a9fnpu.js")
R.c("server/chunks/ssr/[root-of-the-server]__1bddjbu._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1au0nys._.js")
R.c("server/chunks/ssr/src_1t3uyu-._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/src_app_(app)_layout_jsx_02cyl6l._.js")
R.c("server/chunks/ssr/src_app_(app)_template_jsx_0zelj1p._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(app)_lists_[id]_shop_page_actions_1kmizks.js")
R.m(63172)
module.exports=R.m(63172).exports
