var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(auth)/login/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1cxs709._.js")
R.c("server/chunks/ssr/node_modules_09r9c10._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0iiejag.js")
R.c("server/chunks/ssr/[root-of-the-server]__1bddjbu._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1au0nys._.js")
R.c("server/chunks/ssr/src_1t3uyu-._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/src_app_(auth)_layout_jsx_1qgixzi._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(auth)_login_page_actions_1jr42c1.js")
R.m(91756)
module.exports=R.m(91756).exports
